2019-09-27 10:13:54.473950 : D:\PSI-1931\mytest\mini_project\items_upload.py : list index out of range
2019-09-27 10:13:54.614048 : D:\PSI-1931\mytest\mini_project\items_upload.py : list index out of range
2019-09-27 10:13:54.619052 : D:\PSI-1931\mytest\mini_project\items_upload.py : list index out of range
2019-09-27 10:13:54.633062 : D:\PSI-1931\mytest\mini_project\items_upload.py : list index out of range
2019-09-27 10:13:54.638065 : D:\PSI-1931\mytest\mini_project\items_upload.py : list index out of range
2019-09-27 10:35:24.062582 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : unsupported operand type(s) for +: 'bool' and 'str'
2019-09-27 10:36:35.773331 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : unsupported operand type(s) for +: 'bool' and 'str'
2019-09-27 10:37:23.917402 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : unsupported operand type(s) for +: 'bool' and 'str'
2019-09-27 10:38:50.927981 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : 'module' object is not callable
2019-09-27 10:40:46.983109 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : can only concatenate str (not "bool") to str
2019-09-27 10:41:54.238707 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : 'module' object is not callable
2019-09-27 10:42:39.228546 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : 'module' object is not callable
2019-09-27 10:45:35.884565 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: '/error_logs/2019-09-26_log.txt'
2019-09-27 10:47:39.963374 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: '/error_logs/2019-09-26_log.txt'
2019-09-27 11:00:53.593019 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : expected string or bytes-like object
2019-09-27 11:02:05.865166 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : expected string or bytes-like object
2019-09-27 11:15:26.086475 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : not enough values to unpack (expected 2, got 1)
2019-09-27 11:16:54.038718 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : not enough values to unpack (expected 2, got 1)
2019-09-27 11:17:21.371063 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : not enough values to unpack (expected 2, got 1)
2019-09-27 11:18:28.120300 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : cannot process flags argument with a compiled pattern
2019-09-27 11:52:59.253522 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: 'D:\\PSI-1931\\mytest\\mini_project\\error_logs\\2019-09-25_log.txt'
2019-09-27 11:53:55.333209 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : not enough values to unpack (expected 2, got 1)
2019-09-27 13:07:14.014456 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : fullmatch() missing 1 required positional argument: 'string'
2019-09-27 13:07:15.742678 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : fullmatch() missing 1 required positional argument: 'string'
2019-09-27 13:08:16.566723 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: 'D:\\PSI-1931\\mytest\\mini_project\\error_logs\\2019-12-09_log.txt'
2019-09-27 13:09:17.086553 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: 'D:\\PSI-1931\\mytest\\mini_project\\error_logs\\0002-2-2_log.txt'
2019-09-27 13:18:12.740631 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: 'D:\\PSI-1931\\mytest\\mini_project\\error_logs\\2019-09-28_log.txt'
2019-09-27 13:18:15.388518 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: 'D:\\PSI-1931\\mytest\\mini_project\\error_logs\\2019-09-28_log.txt'
2019-09-27 13:18:41.317855 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: 'D:\\PSI-1931\\mytest\\mini_project\\error_logs\\2019-09-28_log.txt'
2019-09-27 13:21:01.309927 : D:/PSI-1931/mytest/mini_project/search_error_logs.py : [Errno 2] No such file or directory: 'D:\\PSI-1931\\mytest\\mini_project\\error_logs\\2019-09-28_log.txt'
